version: "3.8"

services:
    app:
        container_name: desafio-php
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        command: sh /var/www/docker/init.sh
        networks:
            - api-desafio

    webserver:
        image: nginx:latest
        container_name: desafio-nginx
        ports:
            - "8065:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - api-desafio

    db:
        image: mariadb:11.0
        container_name: desafio-mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: '${MYSQL_DATABASE:-desafio}'
            MYSQL_USER: '${MYSQL_USER:-root}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD:-password}' # Altere para a senha desejada
        volumes:
            - ./.docker/bancos/mysql/latest:/var/lib/mysql
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "3309:3306"
        expose:
            - 3309
        networks:
            - api-desafio

networks:
    api-desafio:
        name: desafio
        driver: bridge
