version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./app:/var/www/html
        depends_on:
            - db
        command: sh /var/www/html/docker/init.sh

    webserver:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./app:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app
    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
